packages:
  - carbon-components-ember
  - test-app
  - docs-app
allowBuilds:
  '@carbon/charts': set this to true or false
  '@carbon/colors': set this to true or false
  '@carbon/feature-flags': set this to true or false
  '@carbon/grid': set this to true or false
  '@carbon/icon-helpers': set this to true or false
  '@carbon/icons': set this to true or false
  '@carbon/layout': set this to true or false
  '@carbon/motion': set this to true or false
  '@carbon/styles': set this to true or false
  '@carbon/themes': set this to true or false
  '@carbon/type': set this to true or false
  '@carbon/utils-position': set this to true or false
  '@ibm/plex-mono': set this to true or false
  '@ibm/plex-sans': set this to true or false
  '@ibm/plex-sans-arabic': set this to true or false
  '@ibm/plex-sans-devanagari': set this to true or false
  '@ibm/plex-sans-thai-looped': set this to true or false
  '@ibm/plex-serif': set this to true or false
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  fsevents: set this to true or false
  puppeteer-chromium-resolver: set this to true or false
  unrs-resolver: set this to true or false
