/**
 * Debugging:
 *   https://eslint.org/docs/latest/use/configure/debug
 *  ----------------------------------------------------
 *
 *   Print a file's calculated configuration
 *
 *     npx eslint --print-config path/to/file.js
 *
 *   Inspecting the config
 *
 *     npx eslint --inspect-config
 *
 */
import babelParser from '@babel/eslint-parser';
import js from '@eslint/js';
import { defineConfig, globalIgnores } from 'eslint/config';
import prettier from 'eslint-config-prettier';
import ember from 'eslint-plugin-ember/recommended';
import emberTemplateLintMigration from 'eslint-plugin-ember/configs/template-lint-migration';
import importPlugin from 'eslint-plugin-import';
import n from 'eslint-plugin-n';
import qunit from 'eslint-plugin-qunit';
import globals from 'globals';
import ts from 'typescript-eslint';

const esmParserOptions = {
  ecmaFeatures: { modules: true },
  ecmaVersion: 'latest',
};

const tsParserOptions = {
  projectService: true,
  tsconfigRootDir: import.meta.dirname,
};

export default defineConfig([
  globalIgnores([
    'dist/',
    'dist-*/',
    'declarations/',
    'coverage/',
    'storybook-static/',
    '!**/.*',
    // generated by `pnpm create-autogenerated-files`
    'src/components/icons/',
  ]),
  js.configs.recommended,
  prettier,
  ember.configs.base,
  ember.configs.gjs,
  ember.configs.gts,
  // Template rules: the equivalent of ember-template-lint's `recommended`
  // preset, which this replaces (ember-template-lint is being deprecated in
  // favour of eslint-plugin-ember, emberjs/rfcs#1214).
  ...emberTemplateLintMigration,
  {
    rules: {
      'ember/template-no-inline-styles': 'warn',
      'ember/template-no-positive-tabindex': 'warn',
      'ember/no-legacy-helper-imports': 'error',
    },
  },
  /**
   * https://eslint.org/docs/latest/use/configure/configuration-files#configuring-linter-options
   */
  {
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      parser: babelParser,
    },
  },
  {
    files: ['**/*.{js,gjs}'],
    languageOptions: {
      parserOptions: esmParserOptions,
      globals: {
        ...globals.browser,
      },
    },
  },
  {
    files: ['**/*.{ts,gts}'],
    languageOptions: {
      parser: ember.parser,
      parserOptions: tsParserOptions,
      globals: {
        ...globals.browser,
      },
    },
    extends: [
      ...ts.configs.recommendedTypeChecked,
      // https://github.com/ember-cli/ember-addon-blueprint/issues/119
      {
        ...ts.configs.eslintRecommended,
        files: undefined,
      },
      ember.configs.gts,
    ],
    plugins: {
      import: importPlugin,
    },
    rules: {
      // Type-only imports must be erased from the build; otherwise rollup
      // reports unused externals and phantom circular dependencies. Types
      // always go in their own `import type { ... }` statement.
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { fixStyle: 'separate-type-imports', disallowTypeAnnotations: false },
      ],
      'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
      'ember/template-no-deprecated': 'error',
      // Signature conventions; see AGENTS.md.
      'no-restricted-syntax': [
        'error',
        {
          selector: 'TSTypeAliasDeclaration[id.name=/Signature$/]',
          message: 'Declare signatures with `interface`.',
        },
        {
          selector:
            "TSInterfaceDeclaration[id.name=/Signature$/] > TSInterfaceBody > TSPropertySignature[key.name='Element'] TSNullKeyword",
          message: 'Leave out `Element` when nothing spreads `...attributes`.',
        },
        {
          selector:
            "TSInterfaceDeclaration[id.name=/Signature$/] > TSInterfaceBody > TSPropertySignature[key.name='Args'] > TSTypeAnnotation > TSTypeReference",
          message:
            "Declare `Args` inline; elsewhere refer to them as `<Name>Signature['Args']`.",
        },
        {
          selector:
            "TSInterfaceDeclaration[id.name=/Signature$/] > TSInterfaceBody > TSPropertySignature[key.name='Blocks'] TSTupleType > :not(TSNamedTupleMember, TSTypeLiteral)",
          message: 'Label block params: `default: [item: Item]`.',
        },
      ],
    },
  },
  {
    files: ['src/**/*'],
    plugins: {
      import: importPlugin,
    },
    rules: {
      // require relative imports use full extensions
      'import/extensions': [
        'error',
        'always',
        { ignorePackages: true, checkTypeImports: true },
      ],
    },
  },
  {
    files: ['src/components/**/*.gts'],
    ignores: ['**/*.stories.gts'],
    rules: {
      'ember/template-require-splattributes': 'error',
    },
  },
  {
    files: ['**/*.stories.{gjs,gts}'],
    rules: {
      // CSF Next's `Story.extend({ args })` isn't EmberObject.extend().
      'ember/avoid-leaking-state-in-ember-objects': 'off',
      // Story templates read Storybook's `args` from the render function's
      // scope (not `this.args`), and ember-storybook's <RenderStory> takes
      // an `@args` argument.
      'ember/template-no-args-paths': 'off',
      'ember/template-no-capital-arguments': 'off',
      // Inline styles lay out the demos; they aren't part of the components.
      'ember/template-no-inline-styles': 'off',
    },
  },
  {
    files: ['tests/**/*-test.{js,gjs,ts,gts}'],
    plugins: {
      qunit,
    },
  },
  {
    files: ['tests/**/*'],
    rules: {
      // Style snapshot tests inject Carbon's stylesheets with <style> tags.
      'ember/template-no-forbidden-elements': [
        'error',
        ['meta', 'html', 'script'],
      ],
      // Bare inputs are test fixtures, not UI.
      'ember/template-require-input-label': 'off',
      // Inline styles size and place test fixtures.
      'ember/template-no-inline-styles': 'off',
    },
  },
  /**
   * CJS node files
   */
  {
    files: ['**/*.cjs'],
    plugins: {
      n,
    },

    languageOptions: {
      sourceType: 'script',
      ecmaVersion: 'latest',
      globals: {
        ...globals.node,
      },
    },
  },
  /**
   * ESM node files
   */
  {
    files: ['**/*.mjs'],
    plugins: {
      n,
    },

    languageOptions: {
      sourceType: 'module',
      ecmaVersion: 'latest',
      parserOptions: esmParserOptions,
      globals: {
        ...globals.node,
      },
    },
  },
]);
