/**
 * A Storybook preset that points the components manifest's imports, which
 * agents read, at the components barrel: every component is a named export
 * there, including those that aren't their file's default export.
 */

import { existsSync, readFileSync } from 'node:fs';

import type { Manifests } from 'storybook/internal/types';

// Generated by `pnpm create-autogenerated-files`.
const barrel = new URL('../src/components.ts', import.meta.url);
const barrelExports = new Set(
  existsSync(barrel)
    ? [...readFileSync(barrel, 'utf8').matchAll(/export \{([^}]*)\}/g)].flatMap(
        (match) =>
          (match[1] ?? '')
            .split(',')
            .map((name) => name.replace(/^\s*default as /, '').trim()),
      )
    : [],
);

export const experimental_manifests = (manifests: Manifests | undefined) => {
  for (const component of Object.values(
    manifests?.components?.components ?? {},
  )) {
    if (barrelExports.has(component.name)) {
      component.import = `import { ${component.name} } from 'carbon-components-ember/components';`;
    }
  }
  return manifests;
};
