export { default as defaultTo } from './default-to.ts'
export { default as generic } from './generic.ts'
export { default as getFn } from './get-fn.ts'
export { default as has } from './has.ts'
export { default as htmlSafe } from './html-safe.ts'
export { default as newObj } from './new-obj.ts'
export { default as or } from './or.ts'
export { default as set } from './set.ts'