name: deploy

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: tag
      uses: ButlerLogic/action-autotag@1.0.2
    - name: release
      uses: Roang-zero1/github-create-release-action@v2.0.2
